name: Black Formatter Check

on:
  push:
      branches:
        - main
  pull_request:
  
jobs:
  black:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Black
        run: |
          pip install black
          
      - name: Run Black
        run: |
          black --check --diff .



# name: Lint
# on: [push, pull_request]

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#       - uses: psf/black@stable
#         with:
#           args: ". --check"
